function y = notch60(x)
%NOTCH60 Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 8.3 and the DSP System Toolbox 8.6.
% Generated on: 30-Jul-2015 09:58:13

persistent Hd;

if isempty(Hd)
    
    N     = 6;    % Order
    F0    = 60;   % Center frequency
    BW    = 0.5;  % Bandwidth
    Apass = 1;    % Passband Ripple (dB)
    Fs    = 256;  % Sampling Frequency
    
    h = fdesign.notch('N,F0,BW,Ap', N, F0, BW, Apass, Fs);
    
    Hd = design(h, 'cheby1', ...
        'SOSScaleNorm', 'Linf');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);


